### ISSUE TITLE
[MacOS] MC Crash on Launching Instance NoClassDefFoundError: ca/weblite/objc/Client

### ISSUE THREAD

**Issue by coolsimulations** [gorilla-devs/GDLauncher-Carbon#323]
Installed the new Carbon GDLauncher (v 2.0.6) on MacOS 10.15.7. Tried running both forge and vanilla instances of 1.19.2 only to get the following crash message (potentially a missing library?)

Forge:
```java
java.lang.NoClassDefFoundError: ca/weblite/objc/Client
	at com.mojang.blaze3d.platform.MacosUtil.m_231133_(MacosUtil.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.9.jar%2387!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2385!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.ClassNotFoundException: ca.weblite.objc.Client
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 17 more
```
Vanilla:
```java
java.lang.NoClassDefFoundError: ca/weblite/objc/Client
	at dzm.a(SourceFile:40)
	at efu.<init>(SourceFile:490)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
Caused by: java.lang.ClassNotFoundException: ca.weblite.objc.Client
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```
System Details:
```java
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2629309776 bytes (2507 MiB) / 3271557120 bytes (3120 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon Pro Vega 48
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: 0x6869
	Graphics card #0 versionInfo: Revision ID: 0x0000, ROM Revision: 113-D0650E-072, VBIOS Version: 113-D05001A1XG-011, Option ROM Version: 113-D05001A1XG-011, EFI Driver Version: 01.01.072
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 32768.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 73728.00
	Virtual memory used (MB): 28453.86
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx8192m -Xms1024m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
```
GDLauncher Log:
[2024-04-03_17-53-28.log](https://github.com/gorilla-devs/GDLauncher-Carbon/files/14848168/2024-04-03_17-53-28.log)

**Comment by kevinbevers** [comment]
I'm experiencing identical issue.

**Comment by blarfoon** [comment]
Do other launchers/legacy launcher work? If so, could you provide more details?

**Comment by kevinbevers** [comment]
> Do other launchers/legacy launcher work? If so, could you provide more details?

Minecraft's own launcher works.
changing runtimes has seems to have no effect, except for running Java 8, which shows me a crash report because of the mods i'm using. (the mods don't support java 8)

**Comment by coolsimulations** [comment]
> Do other launchers/legacy launcher work? If so, could you provide more details?

Been a long time user of GDLauncher, worked perfectly fine in the now legacy launcher. Also a user of MultiMC and Technic which work fine.

**Comment by Bass2style** [comment]
i see that you are you getting issues with MC 1.19, are you getting this problem only with 1.19.x instances ? because i can't run 1.19 packs on Carbon (cf #309), but i can run other MC versions (tbh, only tested 1.8.9 and 1.20.x, and few 1.19 packs), and the same 1.19 packs are running on the OG GDL Launcher.

**Comment by kevinbevers** [comment]
> i see that you are you getting issues with MC 1.19, are you getting this problem only with 1.19.x instances ? because i can't run 1.19 packs on Carbon (cf #309), but i can run other MC versions (tbh, only tested 1.8.9 and 1.20.x, and few 1.19 packs), and the same 1.19 packs are running on the OG GDL Launcher.

I have this issue with 1.20.4

**Comment by coolsimulations** [comment]
I don't know if the issue was addressed in the recent v2.0.7 update, but it still persists in that version too. I tested with a fresh installation of Forge 1.19.2-43.3.13. However, a new installation of Forge 1.20.4-49.0.49 worked and so did a new installation of Forge 1.19.4-45.2.15, so it seems to be localised to 1.19.2.

**Comment by yuriygr** [comment]
I had the same problem on version 1.21 in modrinth

**Comment by qwlkx** [comment]
> I had the same problem on version 1.21 in modrinth

me too bro I'm going crazy

**Comment by yuriygr** [comment]
> > I had the same problem on version 1.21 in modrinth
> 
> me too bro I'm going crazy

Try to downgrade modrinth to 0.8.2

**Comment by eliancode** [comment]
Yeah same issue in Modrinth v0.8.5 Fabric 1.20.1

**Comment by Gogo-a** [comment]
Same here. i have been using modrinth for a while now but some of my modpacks started having this issue and its gotten progressavly worse and now i cant even launch vannila. can anyone help!

**Comment by grinheckerdev** [comment]
Wow! This looks like a common issue on Modrinth rn, since I have it too! I made a[ bug report on the Modrinth discord](https://discord.com/channels/734077874708938864/1282262770036768823), yet still no answer. I also just made a bug report on the Modrinth GitHub. I mentioned this thread in the issue, hope it gets attention.

**Comment by Gogo-a** [comment]
ca.weblite.objc.Client and NoClassDefFoundError seems to be the problem but i have spent the last few hours serching how to fix it and i found nothing. Ive tryed it on windows and its fine. so ive narrowed it down to the macOS app itself. i dont know what to do.

**Comment by Gogo-a** [comment]
I reinstalled Modrinth. It seems like this problem is fixed on the latest version (0.8.7)! I just reinstalled java 17 from settings and it works fine! i hope this helped.

**Comment by blarfoon** [comment]
Does this still happen on latest GDL 2.0.20? We use a very similar metadata system to modrinth so if they fixed we might have as well

**Comment by blarfoon** [comment]
Closing due to inactivity, the metadata system has changed a lot since. Reopen if it still happens on the latest version.
