### ISSUE TITLE
"Ads Personalization & Data" not working on Linux

### ISSUE THREAD

**Issue by TheKodeToad** [gorilla-devs/GDLauncher-Carbon#344]
**Version:** 2.0.20 (AppImage)
**Operating System:** Fedora Linux 40 (Workstation Edition)

When going to Settings -> Privacy and pressing Manage next to Ads Personalization & Data, nothing opens.

This is also visible in the log.
```
19:16:36.147 › Error occurred in handler for 'openCMPWindow': TypeError: Cannot read properties of undefined (reading 'openCMPWindow')
    at /tmp/.mount_GDLaunVBf7ym/resources/app.asar/dist/main/index.cjs:105:40935
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
    at WebContents.emit (node:events:517:28)
    at WebContents.emit (node:domain:489:12)
    at i.emit (/tmp/.mount_GDLaunVBf7ym/resources/app.asar/dist/main/index.cjs:42:200016)
```
I would assume this traces back to this line which doesn't seem to do a nullish check:
https://github.com/gorilla-devs/GDLauncher-Carbon/blob/1e9527b46233dbcccecee903c9a064866f841ef5/apps/desktop/packages/main/index.ts#L625

I guess this isn't available on Linux? Maybe hide the button.

**Comment by blarfoon** [comment]
Yes I think this is a mistake in my end. Linux doesn't have dynamic ads so that button should be a no-op

**Comment by blarfoon** [comment]
will be fixed soon, althought I am still working on other fixes so I don't have an ETA yet

**Comment by blarfoon** [comment]
Fixed in the next release: the Manage button no longer breaks on Linux, and the consent manager options are hidden on platforms where it isn't available.
